# Generated by Django 3.2 on 2024-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_completed_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='completed_work',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='journal',
            name='ececutor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='journal',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='journal',
            name='problem',
            field=models.TextField(default='Заглушка', verbose_name='Проблема'),
        ),
    ]
